export {Navigation} from './navigation'
export {Skills} from './skills'
export {Hobbies} from './hobbies'
export {Interests} from './interests'
export {Education} from './education'
export {Experience} from './experience'
export {Contacts} from './contacts'
export {Controls} from './controls'