export {SkillsSection} from './skills-section'
export {HobbiesSection} from './hobbies-section'
export {SoftSkillsSection} from './softskills-section'
export {ContactsSection} from './contacts-section'
export {EducationSection} from './education-section'
export {ExperienceSection} from './experience-section'
export {InterestsSection} from './interests-section'
export {LanguagesSection} from './languages-section'